site_name: Start AQA Python
theme: github
site_url: https://tokyrylo.github.io/aqa/
plugins:
  - glightbox

nav:
  - Home: index.md
  - Первые шаги: 
    - Установка: getting_started/install.md
    - Запуск первой программы: getting_started/start_program.md
  - Основы языка:
    - Переменные: getting_started/variables.md
    - Типы данных: getting_started/data_types.md
    - Операторы: getting_started/operators.md
    - Ввод данных: getting_started/input.md
    - Мини задача: getting_started/final_task.md
  - Управляющие конструкции:
    - If/else: control-flow/if-else.md
    - Циклы: control-flow/for-while.md
    - Мини задача: control-flow/final_task.md
  - Функции:
    - Зачем нужна функция: functions/index.md
    - Как писать свои функции: functions/creating.md
    - Аргументы и возвращаемые значения: functions/args.md
    - Практика функция проверки логина и пароля.: functions/final_task.md
  - Работа с коллекциями:
    - Списки, кортежи, словари: collections/index.md
    - Как хранить и перебирать данные: collections/final_task.md
    - Практика создание список пользователей и проверка, зарегистрирован ли человек: collections/final_task.md
  - Работа с файлами:
    - Чтение и запись файлов: files/index.md
    - Практика сохранить результаты теста в файл: files/final_task.md
  - Ошибки и отладка:
    - Типичные ошибки новичков: errors/index.md
    - Как читать текст ошибки: errors/final_task.md
    - try / except: errors/try-except.md
  - Введение в тестирование:
    - Что такое юнит-тесты и автоматизация: testing/index.md
    - Библиотека unittest: testing/final_task.md
    - Простейший автотест: testing/final_task.md
  - Первые шаги в AQA:
    - Установка pytest: aqa/index.md
    - Структура тестов: aqa/final_task.md
    - Написание первых тестов: aqa/final_task.md
  - Работа с браузером (Selenium / Playwright):
    - Установка Selenium: browser/index.md
    - Первый тест, открыть страницу и проверить заголовок.: browser/final_task.md
  - Работа с API:
    - Установка requests: api/index.md
    - GET и POST запросы: api/final_task.md
    - Проверка ответа API: api/final_task.md
  - Организация проекта:
    - Как хранить тесты: project-structure/index.md
    - Запуск тестов: project-structure/final_task.md
    - Отчеты: project-structure/final_task.md
  - Следующие шаги:
    - Git и GitHub: next-steps/index.md
    - CI/CD: next-steps/final_task.md
    - Контейнеры (Docker): next-steps/final_task.md